name: Auto Translate

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write


jobs:
  convert:
    runs-on: ubuntu-latest

    if: github.actor != 'github-actions[bot]'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Install LibreOffice
        run: sudo apt-get update && sudo apt-get install -y libreoffice


      - name: Convert FODT files to ODT
        run: |
          find docs-en -type f -name "*.fodt" | while read file; do
            echo "Converting $file"
            outdir="$(dirname "$file")"
            mkdir -p docs-en/odt
            project_dirname="$(basename "$outdir")"
            timeout 60s libreoffice --headless --convert-to odt "$file" --outdir "docs-en/odt/$project_dirname"
          done


      - name: Sync Crowdin files
        uses: crowdin/github-action@v1
        with:
          upload_sources: true
          upload_translations: false
          download_translations: true
          crowdin_branch_name: main
          localization_branch_name: translations
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.CROWDIN_GITHUB_TOKEN }}

         
      - name: Create or Update LibreOffice Config
        run: |
          # Define the trusted directory
          cat ~/.config/libreoffice/4/user/registrymodifications.xcu
          pwd         
          # Create the LibreOffice user profile directory if it doesn't exist
          mkdir -p ~/.config/libreoffice/4/user/  # Adjust '4' if using a different major version
          cp -f $GITHUB_WORKSPACE/config/registrymodifications.xcu ~/.config/libreoffice/4/user          
          cat ~/.config/libreoffice/4/user/registrymodifications.xcu


      - name: Install libreoffice macros
        run: |
          mkdir -p ~/.config/libreoffice/4/user/basic/Standard
          cp macros/Module1.xba ~/.config/libreoffice/4/user/basic/Standard/Module1.xba
          cp macros/script.xlb ~/.config/libreoffice/4/user/basic/Standard/script.xlb

          
      - name: Update all FODT file links
        run: |
          find docs-en docs-fr -type f -name "*.fodt" | while read file; do
            echo "Updating links in $file"
            timeout 60s libreoffice --headless --invisible "macro:///Standard.Module1.SaveAndExitDocument" "$file"
          done

  
      - name: Copy image folders
        run: |
          docs_directories="$(ls docs/)"
          for current_docs_dir in $docs_directories; do
            find images -type f -name "*" | while read file; do
              outdir="$(dirname "$file")"
              outdir2="$(dirname "$outdir")"
              outdir3="$(dirname "$outdir2")"
              project_dirname="$(basename "$outdir")"
              project_dirname2="$(basename "$outdir2")"
              project_dirname3="$(basename "$outdir3")"
              
              if [[ "$project_dirname3" != "en-US" ]]; then
                cp -fr $outdir docs/$project_dirname3/fodt/$project_dirname2
                echo copied: $outdir to: docs/$project_dirname3/fodt/$project_dirname2
              fi
            done
          done



      - name: Convert English FODT files to PDF
        run: |
          find docs-en -type f -name "*.fodt" | while read file; do
            echo "Converting $file"
            outdir="$(dirname "$file")"
            project_dirname="$(basename "$outdir")"
            mkdir -p docs-en/pdf
            timeout 60s libreoffice --headless --convert-to pdf "$file" --outdir "docs-en/pdf/$project_dirname"
          done


      - name: Convert Other Language ODT files to FODT
        run: |
          dirs="$(ls docs/)"
          for dir in $dirs; do
            find docs/$dir -type f -name "*.odt" | while read file; do
              echo "Converting $file"
              outdir="$(dirname "$file")"
              project_dirname="$(basename "$outdir")"
              mkdir -p docs/$dir/fodt
              timeout 60s libreoffice --headless --convert-to fodt "$file" --outdir docs/$dir/fodt/$project_dirname
            done
          done


      - name: Convert Other Language FODT files to PDF
        run: |
          dirs="$(ls docs/)"
          for dir in $dirs; do
            find docs/$dir -type f -name "*.fodt" | while read file; do         
              echo "Converting $file"
              outdir="$(dirname "$file")"
              project_dirname="$(basename "$outdir")"
              mkdir -p docs/$dir/pdf
              timeout 60s libreoffice --headless --convert-to pdf "$file" --outdir docs/$dir/pdf/$project_dirname
            done
          done


      - name: Upload EN PDFs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: english-pdfs
          path: docs-en/pdf

      - name: Upload non-EN PDFs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: non-english-pdfs
          path: docs/**/pdf/
          
      - name: Commit and push (git)
        run: | 
          sudo chown -R "$USER" .git
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --staged --quiet || git commit -m "chore: add generated files [skip ci]"
          git push --set-upstream origin translations
